### ISSUE TITLE
UI tests in modules

### ISSUE THREAD

**Issue by jraska** [jraska/github-client#436]
- Shared folder to all be executed with Firebase 
- Source dir shoudl work
- Should be possible to execute in isolation

**Comment by marksr12** [comment]
Okay good

**Comment by jraska** [comment]
Issue comment

**Comment by jraska** [comment]
I think the conclusion now is it is not worth to have Activiity/Fragment tests within modules tests, but trying to move as much code out of `Activities`, which would mean AActivity to have only responsibility of
- Delegting to some Binder
- Holding the ViewModel
- Observing ViewState and calling it to Binder

Such `Binder` could be well tested in isolation

**Comment by jraska** [comment]
Resolved by https://github.com/jraska/github-client/pull/504
