### ISSUE TITLE
Firebase RemoteConfig can use 0 to ignore cache

### ISSUE THREAD

**Issue by lordcodes** [jraska/github-client#559]
https://github.com/jraska/github-client/blob/2861e3efa6cb5484710f77efd259a0c021919c7a/app/src/main/java/com/jraska/github/client/FirebaseConfigProxy.kt#L56

It must have been an old issue in the RemoteConfig code. If you look at sources for RemoteConfig you can safely use '0' to always fetch.

They do:

```
expiration = lastSuccessfulFetch + yourInterval
shouldFetch = timeNow >= expiration 
```

Therefore, even if you literally just fetched in the same millisecond as now, specifying an interval of 0 will still trigger a fetch.

They must have changed the code at some point since you found you needed to specify '1'. I had found same thing and found recently 0 could be used, then remembered I had read something similar in your GitHub Client ages ago, so came to find it so I could let you know. It's pretty minor, but means you don't need a comment to explain the reason for 1 second at least.

**Comment by jraska** [comment]
Nice! Thanks for that :) I will remove it. Evenif its minor, it is pretty important - many minor things lead to chaos :)
