### ISSUE TITLE
Question regarding implementing feature module repos in app module

### ISSUE THREAD

**Issue by alvindizon** [jraska/github-client#812]
I saw your talk regarding modularization and it was very great and informative! It also made me think about previous projects that I worked with that implemented modularization. In one project I worked with, there were feature modules which correspond roughly to screens, and they usually contained an interface Repository, but the actual implementation of this Repository is made in the `app` module, which was aware of all modules. I thought it was a clever implementation, since the feature module doesn't really have to depend directly on let's say, the `api` module or `database` module.  On the other hand, I feel like the `app` module will get too bloated at some point with this approach. Do you think this is a good design? Right now, I'm working on an app that might benefit from modularization, and I'd like to know if the previous pattern I worked with would be a good idea to implement on my current app as well.

Thanks again for the talk and for making this project.

**Comment by jraska** [comment]
Hey Alvin, thanks for reaching out! :) 

I'm happy share my opinion and what I've seen.

First to understand a bit:
> there were feature modules which correspond roughly to screens, and they usually contained an interface Repository,

How would one feature module then use an interface from another module without a `feature-api` module?
It sounds like you achieved lighter feature modules by shifting the code into the `:app`, however without `-api` feature modules have to depend on each other directly if I understand it right, which would lead into high dependency graphs - more info on this here: https://github.com/jraska/modules-graph-assert

In all projects I was involved, we try to discourage having anything within the `:app` module as in theory with Hilt it can be almost empty, or with very few code of the component as this repo for example has :)

The reasoning is the following
1. Build time - `:app` module is recompiled on any change and is almost never cached like that
2. Ownership - the `:app` module might be difficult to split between different teams and is hard to see who is responsible for what.
3. Coupling - once the implementations are in one `:app` module (Repository for your case, but really any type of implementation) there is nothing preventing engineers to start connecting things directly across features.

So the proposed solution is the one from the talk you've seen or this repo.

- Have an `-api` module for the code which _needs to be shared_ with as lightweight interfaces as possible - not depending on anything else.
- Have an implementation module with the Repository implementation.
- Inside the implementation module can be Dagger `@Module` or any type of DI you use binding the implementation to the interface.
- The @Module is wired to the `AppComponent` within the `:app` module.

**Comment by alvindizon** [comment]
> How would one feature module then use an interface from another module without a feature-api module?
Indeed, it came to a point where two features depended on each other. We thought of moving the shared code to another module, but having each feature have a `feature-api` module seems more lightweight and elegant.

I totally agree with all your points! I'm eager to try them on our project and see the improvements especially in build time and the ease of adding features. Thanks again for your time!

**Comment by jraska** [comment]
Thank you! I'm happy to hear at some point how did it go :)
